server:
  port: 9090

spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  datasource:
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml