version: '3.1'
services:
  stat-server:
    build: ./stat/statServer/
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SERVER_PORT=9090
      - STATS_SERVER_URL=http://stat-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stats
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  stat-db:
    image: postgres:14-alpine
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root