version: '3.1'
services:
  stat-server:
    build: ./stat/statServer/
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  stat-db:
    image: postgres:14-alpine
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  main-server:
    build: ./main
    depends_on:
      - main-db
      - stat-db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - STAT_SERVER_URL=http://stat-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  main-db:
    image: postgres:14-alpine
    ports:
      - "5333:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  keycloak:
    build: ./keycloak/
    depends_on:
      - main-db
    ports:
      - "8085:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=root
      - KEYCLOAK_USER_PROVIDER_URL=jdbc:postgresql://main-db:5432/ewm
      - KEYCLOAK_USER_PROVIDER_RDBMS=PostgreSQL
      - KEYCLOAK_USER_PROVIDER_USERNAME=postgres
      - KEYCLOAK_USER_PROVIDER_PASSWORD=root

